export const REQUEST = 'TRANSACTIONS/REQUEST';
export const RECEIVE = 'TRANSACTIONS/RECEIVE';
export const REJECT = 'TRANSACTIONS/REJECT';
export const SAVE_TRANSACTIONS = 'TRANSACTIONS/SAVE_TRANSACTIONS';
export const SAVE_PROJECTS = 'TRANSACTIONS/SAVE_PROJECTS';
export const SAVE_FILTER = 'TRANSACTIONS/SAVE_FILTER';
export const SAVE_STATISTICS_OF_PAYMENT_METHOD = 'SAVE_STATISTICS_OF_PAYMENT_METHOD/SAVE_FILTER';